name: Weekly MAS Run

on:
  schedule:
    - cron: '0 23 * * 5'
  workflow_dispatch:

jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger weekly orchestrator
        env:
          WEEKLY_URL: ${{ secrets.WEEKLY_ORCH_URL }}
        run: |
          curl -X POST "$WEEKLY_URL?run_type=weekly" -H "Authorization: Bearer ${{ secrets.ORCH_TOKEN }}"
